spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
# Server configuration
server:
  port: 8888 #set your port
# Logger configuration
logging:
  pattern:
    console: "[%d] [%-5level] %logger : %msg%n"
amazon:
  dynamodb:
    endpoint: "http://localhost:8000/"
  aws:
    accesskey: "access-key"
    secretkey: "secret-key"